### PR TITLE
Use locally downloaded files for password checks.

### PR DESCRIPTION
**Pull request by helluvamatt**
This would require the password files to already be downloaded into the location.

Also, changes to HaveIBeenPwnedExt.cs would be needed to re-enable the menu options. I had made some other changes to this file to handle errors better, so I have left these changes out of this PR.

### CODE REVIEW

**Comment by helluvamatt** [comment]
Troy has released an update to the Pwned Passwords list: https://www.troyhunt.com/ive-just-launched-pwned-passwords-version-2/

The blog post is an excellent read, and I highly suggest reading it. However, here is a summary:

- Added more breaches and removed some bad data. The list is now 500 million unique passwords.
- The list now includes the number of times a particular password appeared in breaches.
- Cloudflare are supporting this with more than just bandwidth, they've contributed an idea to make the lookup tool more secure.
- The lookup tool now uses k-anonymity: you only submit the first 5-characters to the web service, and it returns a list of hashes and their counts.
- API hits are now cached by Cloudflare, so as not to run up the Azure bill for Troy.

This may make it possible to use the API again, instead of downloading the files locally. As in the range 0x00000 - 0xFFFFF there are only 1,048,576 possible subsets returned. Common ones will be cached at Cloudflare. However, there may still be an issue with consuming Troy's Azure bandwidth.

**Comment by andrew-schofield** [comment]
Thanks, I've merged it and corrected a missing "ToUpper" (also it should have re-used the existing http client which sends a custom user agent etc).
The checker dialog needs a minor change to explain that this is safe to use and that your passwords are not sent in an identifiable fashion to HIBP.

**Comment by andrew-schofield** [comment]
This has been released as v1.2.4

**Comment by Ascendor** [comment]
Hm, I would still love to have the local passwords as an additional option. It would benefit both bandwidth and security concerns. What do you think?

**Comment by fpieper** [comment]
@helluvamatt regarding your performance concerns of searching in the local hash file:
It should be possible to implement a binary search using the file seek mechanism.
Reading 150 bytes (2 * 40 byte + x) at an arbitrary seek position should lead to at least one full hash, which then can be used for the binary search.
In the end phase of the binary search it would probably make sense to e.g. read 1 mb of the file.

If I did the math correct, the naive implementation (without 1mb in the end) would take 29 read operations `log2 550000000 ~ 29`.
The optimized version (with 1 mb read in the end) would take 14 read operations (we only need to find the correct 1mb bin)
```
count of 1mb bins = total line count / line count of one 1mb bin
line count of one 1mb bin = size of 1mb bin / size of one line

log2 (count of 1mb bins) = log2 (550000000 / (1000000 / 40 )) ~ 14.4
```
(I ignored the newline and password count byte sizes as they don't change the result much `log2 (550000000 / (1000000 / 50)) ~ 14.7`)

Anyway even 29 read operations are not a big deal nowadays ;) (at least for the use case of this plugin).

Maybe this is helpful and works out, if you want to want to implement the local approach :).
By the way I am not using the plugin - I just came across while researching possible security concerns of the pwned password api.

**Pull request merged**
