### PR TITLE
Feature/hibp apiv3 authentication

### PR DESCRIPTION
**Pull request by jakob-ledermann**
Added API Key to the breach checking for HIPB with usernames.

The API Key must be provided by the user as Password of an entry with the name "hipb-apikey".
If there is no API Key provided it does not issue requests, as they will be rejected automatically.

If there is an API Key but the request is still answered with "401 Unauthorized" the check is aborted automatically as any other request will fail with the same result.
The error code 429 is respected and the request is automatically retried up to five times. To achive this I separated the method to check a single username from the loop through the usernames. To handle the abort of the check in this scenario I added two custom exception types which are used to signal the abort request to the looping method.
The automated retry is limited to five times, so we give up if we exceed the rate limit multiple times in a row, as the most likely reason for this is another check running using the same api key. Especially as the retry-after header in each 429 Response is honored.

I was unable to obtain a valid api key from https://haveibeenpwned.com/API/Key for several days, so the functionality is only tested for the cases "no api key provided" and "invalid api key provided".

As I was unable to test with a valid api key I do not know, whether there are further changes necessary related to the shortened response. If yes there are a few ways to achive this:

1. Add query parameter truncateResponse=false
1. Querying all breaches beforehand and linking to the details based on breachname
1. Building a Set of required breachnames and fetching them in a second step, linking them to each breached username

### CODE REVIEW

**Comment by jakob-ledermann** [comment]
should help with #80 and #82

**Comment by andrew-schofield** [comment]
Thanks for this PR, I'll try and take a look at it later this evening.

**Comment by thomasmstein** [comment]
Hi Andrew,
Created the "hibp-apikey" entry with my key as the pwd. However, checking for username fails indicating an invalid api key. Then after closing error message 'No breached entries found'. 
Similar results when checking for 'All breach types'.
Checking for 'Breaches based on password' works.
Thanks
api_error_01

**Comment by jakob-ledermann** [comment]
Unfortunatly I am still not able to obtain an api key. So I can not test whether it should work or not.
Please make sure you are using at least version 1.3.4.
Maybe you have the same issue as #85, which should be resolved in Version 1.3.4

**Comment by andrew-schofield** [comment]
Correct, Version 1.3.4 fixes this issue, and has been tested with a valid API key.

**Pull request merged**
